import type { Metadata } from 'next'
import { Aleo } from 'next/font/google'

const aleo = Aleo({ subsets: ['latin'] })

import './globals.css'
import { classNames } from './utils'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={classNames(aleo.className, 'bg-stone-200 text-stone-900')}
      >
        {children}
      </body>
    </html>
  )
}
