name: Verify
on:
  - push
  - pull_request

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-env

      - name: Lint
        shell: bash
        run: pnpm lint

      - name: Typecheck
        shell: bash
        run: pnpm typecheck

      - name: Test
        shell: bash
        run: pnpm test
